---
title: "ashrae-energy-prediction"
author: "Athanasios Pliousis"
date: "6/22/2020"
output: html_document
editor_options: 
  chunk_output_type: inline
---

```{r setup, fig.width=20, fig.height=13, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(lubridate)
library(scales)
```

```{r}
train_dt <- read_csv('train.csv')

building_meta <- read_csv('building_metadata.csv')
```

## EDA


```{r}
train_dt$timestamp <- lubridate::ymd_hms(train_dt$timestamp)

class(train_dt$timestamp)
```
```{r}
# train_dt[train_dt$meter_reading == max(train_dt$meter_reading),]

train_dt %>% filter(meter_reading == max(meter_reading))
```


```{r}
# building_meta[building_meta$building_id == 1099,]

building_meta %>% filter(building_id == 1099)

summary(building_meta)

summary(train_dt)
```







```{r}
joined <- train_dt %>% 
  full_join(., building_meta, by = "building_id")
```


```{r}
joined$square_meters <- joined$square_feet *  0.09290304 #square meters 


joined$energy_per_sqm <- joined$meter_reading / joined$square_meters

joined %>% summary()
```

```{r}


joined %>% filter(energy_per_sqm == max(energy_per_sqm))

joined %>% filter(energy_per_sqm >= quantile(joined$energy_per_sqm, 0.99))

quantile(joined$energy_per_sqm, 0.99)

joined %>% filter(energy_per_sqm > 0.5) %>% ggplot(aes(energy_per_sqm)) + geom_histogram(binwidth = 1) + coord_cartesian(xlim=c(0,15))

joined %>% filter(building_id == 1099) %>% ggplot(aes(timestamp, meter_reading,color = as.factor(meter))) + geom_line()

joined %>% filter(building_id == 1099, meter == 0) %>% ggplot(aes(timestamp, meter_reading)) + geom_line()

joined %>% filter(building_id == 1099, meter == 2) %>% ggplot(aes(timestamp, meter_reading)) + geom_line()

joined %>% filter(meter == 2) %>% ggplot(aes(timestamp, meter_reading, color =)) + geom_line()

joined %>% count(site_id) %>%  ggplot(aes(site_id, n)) + geom_col() + scale_y_continuous(labels = comma)



```



```{r fig.height=9,fig.width=16}
joined %>% filter(meter == 3) %>%  ggplot(aes(timestamp, meter_reading)) + geom_line() + facet_wrap(~ site_id, scales="free_y")

```


```{r fig.height=9,fig.width=16}
joined %>% filter(meter == 3) %>%  ggplot(aes(timestamp, energy_per_sqm)) + geom_line() + facet_wrap(~ site_id, scales = "free_y")
```

